"""Create the database schema and load reference / demo data.

Usage
-----
    python -m scripts.seed              # schema + bootstrap TPM + master data
    python -m scripts.seed --demo       # also load the node inventory and users
    python -m scripts.seed --reset      # drop everything first (destructive)
"""
from __future__ import annotations

import argparse
import random
import sys
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import select  # noqa: E402
from sqlalchemy.orm import Session  # noqa: E402

from app.core.config import settings  # noqa: E402
from app.core.database import Base, SessionLocal, engine, init_db  # noqa: E402
from app.core.security import hash_password  # noqa: E402
from app.models import (  # noqa: E402
    ActivityLog,
    ActivityMaster,
    ActivityStatus,
    AssignmentRole,
    Circle,
    DeploymentState,
    Node,
    NodeActivity,
    NodeAssignment,
    NodeStatus,
    Product,
    User,
    UserRole,
)
from scripts.seed_data import (  # noqa: E402
    ACTIVITIES,
    CIRCLES,
    DEMO_PASSWORD,
    DEMO_USERS,
    PRODUCTS,
    circle_for,
    product_for,
    unique_node_names,
)

#: Deployment state implied by how far a node has progressed through the
#: seven-step workflow.
PROGRESS_STATES = [
    DeploymentState.PLANNED,       # 0 activities complete
    DeploymentState.IN_PROGRESS,   # 1
    DeploymentState.IN_PROGRESS,   # 2
    DeploymentState.INTEGRATION,   # 3
    DeploymentState.INTEGRATION,   # 4
    DeploymentState.ACCEPTANCE,    # 5
    DeploymentState.ACCEPTANCE,    # 6
    DeploymentState.LIVE,          # 7 -- every step signed off
]


def _get_or_create(db: Session, model, defaults: dict | None = None, **lookup):
    instance = db.execute(select(model).filter_by(**lookup)).scalar_one_or_none()
    if instance is not None:
        return instance, False
    instance = model(**lookup, **(defaults or {}))
    db.add(instance)
    db.flush()
    return instance, True


def seed_master_data(db: Session) -> None:
    for name in PRODUCTS:
        _get_or_create(db, Product, {"is_active": True}, product_name=name)
    for name in CIRCLES:
        _get_or_create(db, Circle, {"is_active": True}, circle_name=name)
    for name, description in ACTIVITIES:
        _get_or_create(
            db,
            ActivityMaster,
            {"description": description, "is_active": True},
            activity_name=name,
        )
    print(
        f"  master data: {len(PRODUCTS)} products, {len(CIRCLES)} circles, "
        f"{len(ACTIVITIES)} activities"
    )


def seed_bootstrap_user(db: Session) -> User:
    admin, created = _get_or_create(
        db,
        User,
        {
            "name": settings.first_tpm_name,
            "password_hash": hash_password(settings.first_tpm_password),
            "mobile_number": settings.first_tpm_mobile,
            "role": UserRole.TPM,
            "is_active": True,
        },
        username=settings.first_tpm_username,
    )
    print(
        f"  bootstrap TPM: {admin.username} "
        f"({'created' if created else 'already present'})"
    )
    return admin


def seed_demo_users(db: Session) -> list[User]:
    users = []
    for name, username, role, mobile in DEMO_USERS:
        user, _ = _get_or_create(
            db,
            User,
            {
                "name": name,
                "password_hash": hash_password(DEMO_PASSWORD),
                "mobile_number": mobile,
                "role": role,
                "is_active": True,
            },
            username=username,
        )
        users.append(user)
    roles = ", ".join(f"{u.name} ({u.role})" for u in users)
    print(f"  demo users: {roles} -- password '{DEMO_PASSWORD}'")
    return users


def _write_artifact(activity: NodeActivity, node: Node, uploader: User) -> ActivityLog:
    """Write a real evidence file so a Completed activity satisfies the rule.

    The seeder does not bypass the completion rule -- it uploads an artifact the
    same way the application does, then marks the activity complete.
    """
    storage_root = Path(settings.storage_dir)
    folder = storage_root / f"activity_{activity.id}"
    folder.mkdir(parents=True, exist_ok=True)

    activity_name = activity.activity_master.activity_name
    slug = activity_name.lower().replace(" ", "_")
    display_name = f"{node.node_name}_{slug}_evidence.txt"
    stored_name = f"{uuid.uuid4().hex}_{display_name}"

    body = (
        f"NNM artifact\n"
        f"============\n"
        f"Node     : {node.node_name}\n"
        f"Activity : {activity_name}\n"
        f"Engineer : {uploader.name}\n"
        f"Result   : PASS\n\n"
        f"Sample evidence generated by scripts/seed.py for demonstration.\n"
        f"Replace it with the real artifact for this step.\n"
    ).encode("utf-8")

    (folder / stored_name).write_bytes(body)

    return ActivityLog(
        node_activity_id=activity.id,
        file_name=display_name,
        file_path=f"activity_{activity.id}/{stored_name}",
        content_type="text/plain",
        file_size=len(body),
        uploaded_by=uploader.id,
        uploaded_at=activity.completed_date or datetime.now(timezone.utc),
    )


def seed_nodes(db: Session, admin: User, users: list[User]) -> None:
    if db.execute(select(Node).limit(1)).scalar_one_or_none() is not None:
        print("  nodes: skipped (the inventory is already loaded)")
        return

    rng = random.Random(20260922)
    products = {p.product_name: p for p in db.execute(select(Product)).scalars()}
    circles = {c.circle_name: c for c in db.execute(select(Circle)).scalars()}
    masters = [
        db.execute(
            select(ActivityMaster).where(ActivityMaster.activity_name == name)
        ).scalar_one()
        for name, _ in ACTIVITIES
    ]

    leads = [u for u in users if u.role == UserRole.LEAD] or [admin]
    tpms = [u for u in users if u.role == UserRole.TPM] or [admin]
    engineers = [u for u in users if u.role == UserRole.ENGINEER] or [admin]

    now = datetime.now(timezone.utc)
    node_names = unique_node_names()
    total_activities = 0
    total_logs = 0

    for index, node_name in enumerate(node_names):
        circle = circles[circle_for(node_name)]
        product = products[product_for(node_name)]
        owner = engineers[index % len(engineers)]

        node = Node(
            node_name=node_name,
            product_id=product.id,
            circle_id=circle.id,
            owner_id=owner.id,
            lead_id=leads[index % len(leads)].id,
            tpm_id=tpms[index % len(tpms)].id,
            deployment_state=DeploymentState.PLANNED,
            overall_status=NodeStatus.NOT_STARTED,
            created_at=now - timedelta(days=rng.randint(5, 120)),
        )
        db.add(node)
        db.flush()

        # Assignments: every node has a primary owner; a secondary owner and a
        # support engineer are added less often. Staffing every node with every
        # engineer would leave nobody read-only anywhere, which is neither
        # realistic nor a useful demonstration of the permission rules.
        staffing = [(AssignmentRole.PRIMARY_OWNER, 1.0)]
        if len(engineers) > 1:
            staffing.append((AssignmentRole.SECONDARY_OWNER, 0.6))
        if len(engineers) > 2:
            staffing.append((AssignmentRole.SUPPORT_ENGINEER, 0.35))

        for offset, (role, likelihood) in enumerate(staffing):
            if likelihood < 1.0 and rng.random() > likelihood:
                continue
            db.add(
                NodeAssignment(
                    node_id=node.id,
                    user_id=engineers[(index + offset) % len(engineers)].id,
                    role=role,
                    assigned_by=admin.id,
                )
            )

        # Progress: the first `done` steps are signed off, the next one is in
        # flight, and the rest are still pending.
        done = rng.randint(0, len(masters))
        started = node.created_at

        for step, master in enumerate(masters):
            if step < done:
                status = ActivityStatus.COMPLETED
                start_date = started + timedelta(days=step * 2)
                completed_date = start_date + timedelta(days=rng.randint(1, 4))
            elif step == done:
                status = ActivityStatus.IN_PROGRESS
                start_date = started + timedelta(days=step * 2)
                completed_date = None
            else:
                status = ActivityStatus.PENDING
                start_date = None
                completed_date = None

            activity = NodeActivity(
                node_id=node.id,
                activity_master_id=master.id,
                assigned_to=engineers[(index + step) % len(engineers)].id,
                status=status,
                start_date=start_date,
                completed_date=completed_date,
                remarks=None,
            )
            db.add(activity)
            db.flush()
            total_activities += 1

            if status == ActivityStatus.COMPLETED:
                db.add(_write_artifact(activity, node, activity.assignee or owner))
                total_logs += 1

        node.deployment_state = PROGRESS_STATES[done]
        node.overall_status = (
            NodeStatus.COMPLETED
            if done == len(masters)
            else NodeStatus.NOT_STARTED
            if done == 0
            else NodeStatus.IN_PROGRESS
        )

    db.flush()
    print(
        f"  nodes: {len(node_names)} nodes, {total_activities} activities, "
        f"{total_logs} uploaded artifacts"
    )
    skipped = len(unique_node_names()) - len(node_names)
    if skipped:  # pragma: no cover - defensive
        print(f"  note: {skipped} duplicate node names were skipped")


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed the NNM database")
    parser.add_argument(
        "--demo", action="store_true", help="also create demo users and the node inventory"
    )
    parser.add_argument(
        "--reset", action="store_true", help="DROP every table before seeding (destructive)"
    )
    parser.add_argument(
        "--yes", action="store_true", help="skip the confirmation prompt for --reset"
    )
    args = parser.parse_args()

    if args.reset:
        if not args.yes:
            confirm = input("This deletes all NNM data. Type 'yes' to continue: ")
            if confirm.strip().lower() != "yes":
                print("Aborted.")
                return
        Base.metadata.drop_all(bind=engine)
        print("Dropped all tables.")

    print(f"Seeding {settings.database_url}")
    Path(settings.storage_dir).mkdir(parents=True, exist_ok=True)
    init_db()

    with SessionLocal() as db:
        seed_master_data(db)
        admin = seed_bootstrap_user(db)
        if args.demo:
            users = seed_demo_users(db)
            seed_nodes(db, admin, users)
        db.commit()

    print("Seeding complete.")
    print(
        f"Sign in as '{settings.first_tpm_username}' / "
        f"'{settings.first_tpm_password}' and change the password immediately."
    )


if __name__ == "__main__":
    main()
